version: "3.7"
networks:
  dockerapp-network:
    driver: bridge
    labels:
      project: "dockerapp"
      module: "web_app"
    attachable: true
services:
  dockerapp-db:
    # image: "dockerapp-db"
    build:
      context: .
      dockerfile: mysql.dockerfile
    networks:
      - dockerapp-network
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appPassw0rd
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
  dockerapp-nginx:
    # image: "dockerapp-nginx"
    build:
      context: .
      dockerfile: nginx_tomcat.dockerfile
    ports: 
      - "19090:80"
    deploy:
      replicas: 1
  dockerapp-restserver :
    # image: "dockerapp-tomcat"
    build:
      context: .
      dockerfile: tomcat.dockerfile
    networks:
      - dockerapp-network
    ports:
      - "18080:8080"
    environment:
      DOCKERAPP_DB_USER: appuser
      DOCKERAPP_DB_PASSWORD: appPassw0rd
    depends_on:
      - dockerapp-db
    restart: on-failure
    deploy:
      replicas: 1
      